### ISSUE TITLE
Define Call-Hierarchy of Letter/Paperclip/Door/ & Key 

### ISSUE THREAD

**Issue by mvmntjulz** [mkli90/tekmate#41]
The Player should get a warning, if he tries to push the key out of the lock before making save, that it will land on the flyer.
Therefore it should be necessary to combine flyer/door before needle/lock.
If one tries to use needle/lock before flyer/door the Player could response with something like: " This is a bad idea. I will never reach the key, if it falls on the floor behind the door.

**Comment by mkli90** [comment]
=> Look at door 
        => Combine letter/door
            => Combine paperclip/door (delete: letter, paperclip; add: key)
                => Combine key/door 
                   => Use Door
